GMM = 'gmm'
CCGMM = 'ccgmm'
OR_CCGMM = 'or_ccgmm'
AND_CCGMM = 'and_ccgmm'
MEAN_CCGMM = 'mean_ccgmm'
OR_GMM = 'or_gmm'
AND_GMM = 'and_gmm'
MEAN_GMM = 'mean_gmm'
CIFAR10_CLASSES = ['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']
DIVISION_OPTIONS = [GMM, CCGMM, OR_CCGMM, AND_CCGMM, MEAN_CCGMM, OR_GMM, AND_GMM, MEAN_GMM]